### PR TITLE
query null check issue

### PR DESCRIPTION
**Pull request by onpoc**
query null check issue to InboundSms.cs
#hacktoberfest

### CODE REVIEW

**Comment by slorello89** [comment]
Hi @onpoc - thanks for opening this PR - can you relate this to a particular issue? If it's something you're seeing - feel free to open an [Issue](https://github.com/Vonage/vonage-dotnet-sdk/issues)

**Comment by sitecorelibraries** [comment]
Thanks for your valuable comments and coverage reports.
Since I raised pull request to avoid null risk, and after null check will have to update relevant unit test code as well. This way code coverage will have no impact and enhance code too.


If feel, changes are right to enhance COQ (Code of Quality) then can merge.

**Comment by onpoc** [comment]
Thanks for your valuable comments and coverage reports.
Since I raised pull request to avoid null risk, and after null check will have to update relevant unit test code as well. This way code coverage will have no impact and enhance code too.

If feel, changes are right to enhance COQ (Code of Quality) then can merge.

**Review by slorello89 — APPROVED** [review]
@onpoc - thanks for submitting this, will get it merged.

**Pull request merged**
