### PR TITLE
Update NexmoException.cs

### PR DESCRIPTION
**Pull request by ParamGabhawala**
Merge this file with the main file. If any help needs help write to me on paramgabhawala@gmail.com

### CODE REVIEW

**Comment by slorello89** [comment]
Hi @ParamGabhawala,

Thank you for opening this PR, unfortunately, it does not meet the threshold of what we consider a valid PR and I am going to close it.

**Comment by ParamGabhawala** [comment]
Hi @slorello89 

Will I get the swag

**Comment by ParamGabhawala** [comment]
Will I get the developer swag
Pls, answer me.

**Comment by slorello89** [comment]
This PR will not count for the contest. See https://hacktoberfest.digitalocean.com/details for details on the rules of the contest.

**Pull request closed without merging**
